import React, { Component } from 'react';

export default class Chapter4 extends Component {
    render () {
        return (
            <div className='content'>
                <h1>Alternative Confinement Vessels for Fusion Power</h1>
                <h2>Stellarator Machines Eliminate the Mega–Amperes ofPlasma Currents by Using Nonsymmetric Magnetic Field Configurations</h2>
                    <p>Max-Planck Institute for Plasma Physics first in Garching and now in Greifswald, Germany.</p>
                <h2>The Greifswald Stellarator machine W7X makes a breakthrough with <span class="math inline"><strong>10</strong> </span>KeV hydrogen plasma driven by high–power RF heating avoiding the Mega–Amperes of plasma currents</h2>
                    <p>Wendelstein 7–X (W7–X) was operated successfully with the first divertor plasma in the operation phase 1.2a (OP1.2a). A new combined probe head, developed and installed on the multiple–purpose manipulator, is able to measure the edge plasma profiles (<span class="math inline"><em>T</em><sub><em>e</em></sub>, <em>n</em><sub><em>e</em></sub>, <em>ϕ</em><sub><em>f</em></sub>, <em>M</em><sub>∥</sub></span>), variation of magnetic field, poloidal and radial turbulence structures. The Scrape–Off Layer (SOL) plasma parameters in two magnetic configurations (standard and high mirror) are in good agreement with the magnetic island structure and the field line connection length calculated by the field line tracer. In both the standard and high mirror configurations, the radial turbulent heat flux and particle flux have strong dependence on the local magnetic topology, revealing two distinct transport patterns: a broadband turbulence dominant region in the outer SOL and a low–frequency dominant region in the inner SOL. In the standard divertor configuration, the broadband turbulence with a frequency range of 40-120<span class="math inline"> </span>kHz is located near the island center along the probe path, leading to outward transport. These broadband fluctuations propagate with a velocity of 2.3-4.6<span class="math inline"> </span>km/s poloidally along the ion diamagnetic drift direction in the plasma frame, with <span class="math inline"><em>k</em><sub><em>θ</em></sub><em>ρ</em><sub><em>s</em></sub></span>, close to 0.1. The large radial transport induced by the broadband turbulence is accompanied by a steep electron density gradient. The low frequency (0-30<span class="math inline"> </span>kHz) dominant transport exhibits obvious intermittent structure. Some statistical techniques are applied to the characterization of the intermittent transport.</p>
                <h2 >Large Helical Device (LHD) Produces Fusion Power in Japan</h2>
                    <h3>Helical Magnetic Confinement System Invented in Japan — the Large Helical Device (LHD) Produces Fusion Power Deuterium Plasma for 30–minute Steady States</h3>
                        <p>Both the early intro–ELM and inter–ELM periods produce inputs of tungsten and beryllium ions into the core plasma under a variety of conditions. Theoretical modeling and comparisons with data from the fusion tokamaks WEST, EAST, KSTAR (Korea Superconducting Tokamak Advanced Research), JET (Joint European Torus) and DIII–D (Doublet III) show that the inward fluxes of impurity ions and their accumulation conditions are critical issues for ITER. <em>Michoski, et al.</em> (2017) and <em>Michoski and Horton</em> (2019) used theoretical models and simulations for the vessel–wall emission problem combined with drift wave impurity transport formulas. The models interpret the spectroscopic emission data produced by the impurity ions and dust particles crossing the magnetic separatrix to enter the core plasma in tokamaks and in the Large Helical Device. The research produces models for the rate of accumulations of Be and W ions during an ELM event and during minor disruptions. A set of impurity transport equations is solved using formulas for impurity fluxes driven by drift waves with ion particles and hydrogen isotopes. The spectral emission work extends the earlier models from the Alcator C–MOD impurity transport research [<em>Rowan, et al.</em> (2008)] and recent applications to DIII–D impurity injection transport experiments [<em>Houshmandyar, et al.</em> (2016, 2018), <em>Michoski, et al.</em> (2017), <em>Michoski and Horton</em> (2019)].</p>
                        <p>Research extending the earlier development of models for inward turbulent transport of impurities from the first wall and the divertor walls [<em>Don, et al.</em> (1999), <em>Futatani, et al.</em> (2010)] is carried out with experiments in WEST with tungsten divertor walls. Large Helical Device (LHD) data with hydrogen plasmas shows the inward transport of plasma dust particles from <span class="math inline">100 </span>nm to microsized dust particles. The physics of these large negatively–charged dust grains is similar to that of dust transport in deserts of West Texas is closely related to the charged <span class="math inline">$\rm SiO_2$</span> dust that rises from solar heating in Dust Devils. The dust devil models and the codes [<em>Onishchenko, et al.</em> (2014)] are generalized to the plasma dust transport problem.</p>
                        <p>The LHD plasmas provide a data set for comparison with simulations. Studies called TESPEL for dust transport in the WEST and EAST deuterium plasmas. The TESPEL data from <em>Nakamura, et al.</em> (2017) in the Large Helical Device (LHD) injects microsized plastic balls containing the elements with neighboring atomic numbers to the iron and chromium atoms in the vessel walls — namely the three tracer elements <span class="math inline"><em>V</em>(<em>Z</em> = 23), <em>M</em><em>n</em>(<em>Z</em> = 25)</span> and <span class="math inline"><em>C</em><em>o</em>(<em>Z</em> = 27)</span> described in <em>Nakamura, et al.</em> (2014).</p>
                        <p>A major effort in the machine design has been that of producing a plasma column in which a high mean poloidal field <span class="math inline">$\overline B_p\simeq\sqrt{10}\,$</span>T can be reached together with plasma currents <span class="math inline"><em>I</em><sub><em>p</em></sub> ≃ 10</span>-<span class="math inline">11 </span>MA while maintaining reasonable safety factors against the onset of macroscopic instabilities (i.e. <span class="math inline"><em>q</em>(<em>ψ</em><sub><em>a</em></sub>) ≃ 3.6</span>). The rough arguments for this choice of objectives are as follows: High values of the confinement parameter <span class="math inline"><em>n</em><em>τ</em><sub><em>E</em></sub>, <em>n</em></span> being the particle density and <span class="math inline"><em>τ</em><sub><em>E</em></sub></span> the energy replacement time, should be reached considering that the maximum particle density should be related to the average current density <span class="math inline">$\langle J_\|\rangle\sim\overline B_p/\overline a$</span>, where <span class="math inline">$\overline a$</span> is the mean plasma minor radius, and that the confinement time should have a significant dependence on <span class="math inline"><em>I</em><sub><em>p</em></sub></span>. Then the maximum values of <span class="math inline"><em>n</em><em>τ</em><sub><em>E</em></sub></span> should be related to <span class="math inline">$\overline B_p^2$</span> as <span class="math inline">$I_p\simeq 5\overline a\overline B_p$</span>. Moreover, if we consider the mean plasma pressure to be limited by the magnetic pressure <span class="math inline">$\overline B_p^2/(2\mu_0)$</span>, the plasma reactivity represented by <span class="math inline"><em>n</em><sup>2</sup>⟨<em>σ</em><sub><em>f</em></sub><em>v</em>⟩ ∝ <em>n</em><sup>2</sup><em>T</em><sup>2</sup></span> can be expected to be related to <span class="math inline">$\overline B_p^4$</span>. These considerations have in fact been supported by sophisticated numerical simulations that have been carried out by <span class="math inline">1 + 1/2<em>D</em></span> transport codes [<em>Coppi, et al.</em> (2010, 2013), <em>Airoldi and Cenacchi</em> (1997)]. In this connection we observe that well–confined plasmas with maximum densities close to <span class="math inline">$10^{21}\,\rm m^{-3}$</span> have been obtained repeatedly by the Alcator line of experiments and, with lower temperatures, by the Large Helical Device machine. To facilitate the attainment of these densities, the adoption, as in the case of the Alcator C experiments, of a pellet injector is planned. In the case of IGNITOR, however, the required pellet speeds are considerably higher and further advances (expected to be possible) in the technology of these injectors are needed.</p>
            
            </div>
        )
    }
}