import React, { Component } from 'react';
import loadMathJax from './load-mathjax.js';

export default class Chapter5 extends Component {
    
   componentDidMount() {
       loadMathJax();
   }
    render () {
        return (
            <div className='content'>
                <h1>Plasma Confinement with Superconducting Magnetic Field Currents</h1>
                <h2>C–Mod Machine at MIT Uses Superconducting Coils to Produce Record Plasma Confinement</h2>
                    <p>In tokamaks a technique to accurately measure the electron temperature gradient scale length <span className="math inline"><em>L</em><sub><em>T</em><sub><em>e</em></sub></sub> =  − <em>T</em><sub><em>e</em></sub>/∇<em>T</em><sub><em>e</em></sub></span> was developed. The technique is to vary the toroidal magnetic field <span className="math inline"><em>B</em><sub><em>T</em></sub></span> by 1% to a few 2% to slew the ECE channels [<em>Houshmandyar, et al.</em> (2016)]. The measurements are in agreement with the calculation of the gradient scale length <span className="math inline"><em>L</em><sub><em>T</em><sub><em>e</em></sub></sub></span> from the temperature profile. The method captures the fine structures in the <span className="math inline"><em>T</em><sub><em>e</em></sub></span> profiles that are missed in the common fitting techniques [<em>Houshmandyar, et al.</em> (2018)]. The <span className="math inline"><em>T</em><sub><em>e</em></sub>(<em>r</em>, <em>t</em>)</span> measurements using this technique have limited time resolution since rapid modulation of <span className="math inline"><em>B</em><sub><em>T</em></sub></span> is not possible. Additionally, the <span className="math inline"><em>B</em><sub><em>T</em></sub></span> variation is not practical for tokamaks that employ superconducting magnets. Still the method of slewing the ECE channels to measure <span className="math inline">∇<em>T</em><sub><em>e</em></sub></span> and <span className="math inline"><em>L</em><sub><em>T</em><sub><em>e</em></sub></sub></span> works for the plasma dynamics in plasmas with superconducting toroidal machines.</p>
                <h2>A New Version of the MIT C–Mod Machine Developed with Superconducting Coils by the Private Sector Company, Commonwealth Fusion Systems (CFS)</h2>
                    <p>Development of this carbon–free, combustion–free source of energy is now on a faster track toward realization, thanks to a collaboration between MIT and a new private company, Commonwealth Fusion Systems (CFS). CFS will join with MIT to carry out rapid, staged research leading to a new generation of fusion experiments and power plants based on advances in high–temperature superconductors — work made possible by decades of federal government funding for basic research.</p>
                    <p>CFS has attracted an investment of $50 million in support of this effort from the Italian energy company Ente Nazionale Idrocarburi (ENI). In addition, CFS continues to seek the support of additional investors. CFS will fund fusion research at MIT as part of this collaboration, with an ultimate goal of rapidly commercializing fusion energy and establishing a new industry.</p>   
                    <p>Advances in superconducting magnets have put fusion energy potentially within reach, offering the prospect of a safe, carbon–free energy future [<em>MIT President L. Rafael Reif</em>]. As humanity confronts the rising risks of climate disruption, MIT is joining with industrial allies to run full–speed toward this transformative vision for our shared future on Earth.</p>
                    <p>Everyone agrees on the eventual impact and the commercial potential of fusion power, but the question is: How do you get there? Commonwealth Fusion Systems CEO Robert Mumgaard argues that we get there by leveraging the plasma science that is already developed, collaborating with the right partners, and tackling the problems step by step.</p>
                    <p>MIT Vice President for Research Maria Zuber, who has written an op-ed on the importance of this news that appears in today’s Boston Globe, states that “We are grateful for the MIT team that worked tirelessly to form this collaboration. Associate Provost Karen Gleason’s leadership was instrumental — as was the creativity of the Office of the General Counsel, the Office of Sponsored Programs, the Technology Licensing Office, and the MIT Energy Initiative.</p>
                    <h4>Superconducting magnets are key</h4>
                        <p>Fusion, the process that powers the sun and stars, involves light elements, such as hydrogen, smashing together to form heavier elements, such as helium — releasing prodigious amounts of energy in the process. This process produces net energy only at extreme temperatures of hundreds of millions of degrees Celsius, too hot for any solid material to withstand. To get around that, fusion researchers use magnetic fields to hold in place the hot plasma — a kind of gaseous soup of subatomic particles — keeping it from coming into contact with any part of the donut–shaped chamber.</p>
                        <p>The new effort aims to build a compact device capable of generating 100 million watts, or 100 megawatts (MW), of fusion power. This device will, if all goes according to plan, demonstrate key technical milestones needed to ultimately achieve a full–scale prototype of a fusion power plant that could set the world on a path to low–carbon energy. If widely disseminated, such fusion power plants could meet a substantial fraction of the world’s growing energy needs while drastically curbing the greenhouse gas emissions that are causing global climate change.</p>
                        <p>“Today is a very important day for us," says ENI CEO Claudio Descalzi. “Thanks to this agreement, ENI takes a significant step forward toward the development of alternative energy sources with an ever–lower environmental impact. Fusion is the true energy source of the future, as it is completely sustainable, does not release emissions or long–term waste, and is potentially inexhaustible. It is a goal that we are increasingly determined to reach quickly."</p>
                        <p>CFS will support more than $30 million of MIT research over the next three years through investments by ENI and others. This work will aim to develop the world’s most powerful large-bore superconducting electromagnets — the key component that will enable construction of a much more compact version of a fusion device called a tokamak. The magnets, based on a superconducting material that has only recently become available commercially, will produce a magnetic field four times as strong as that employed in any existing fusion experiment, enabling a more than tenfold increase in the power produced by a tokamak of a given size.</p>
                    <h4>Soonest/Smallest Private–Funded Affordable, Robust, Compact Reactor (SPARC) conceived at the MIT office of PSFC</h4>
                        <p>The project was conceived by researchers from MIT’s Plasma Science and Fusion Center, led by PSFC Director Dennis Whyte, Deputy Director Martin Greenwald, and a team that grew to include representatives from across MIT, involving disciplines from engineering to physics to architecture to economics. The core PSFC team included Mumgaard, Dan Brunner PhD 2013, and Brandon Sorbom PhD 2017 — all now leading CFS — as well as Zach Hartwig PhD 2014, now an assistant professor of nuclear science and engineering at MIT.</p>
                        <p>Once the superconducting electromagnets are developed by researchers at MIT and CFS, MIT and CFS will design and build a compact and powerful fusion experiment, called SPARC, using those magnets. The experiment will be used for what is expected to be a final round of research enabling design of the world’s first commercial power–producing fusion plants.</p>
                        <p>SPARC is designed to produce about <span className="math inline">100 </span>MW of heat. While it will not turn that heat into electricity, it will produce, in pulses of about 10 seconds, as much power as is used by a small city. That output would be more than twice the power used to heat the plasma, achieving the ultimate technical milestone: positive net energy from fusion.</p>
                        <p>This demonstration would establish that a new power plant of about twice SPARC’s diameter, capable of producing commercially viable net power output, could go ahead toward final design and construction. Such a plant would become the world’s first true fusion power plant, with a capacity of <span className="math inline">200 </span>MW of electricity, comparable to that of most modern commercial electric power plants. Whyte, Greenwald, and Hartwig state that the implementation could proceed rapidly and with little risk, and such power plants could be demonstrated within 15 years.</p>
                    <h4>SPARC is complementary to ITER</h4>
                        <p>The project is expected to complement the research planned for a large international collaboration called ITER, currently under construction as the world’s largest fusion experiment at a site in southern France. If successful, ITER is expected to begin producing fusion energy around 2035.</p>
                        <p>“Fusion is way too important for only one track," says Greenwald, who is a senior research scientist at PSFC.</p>
                        <p>By using magnets made from the newly available superconducting material — a steel tape coated with a compound called yttrium–barium–copper oxide (YBCO) — SPARC is designed to produce a fusion power output about a fifth that of ITER, but in a device that is only about 1/65 the volume, Hartwig says. The ultimate benefit of the YBCO tape, he adds, is that it drastically reduces the cost, timeline, and organizational complexity required to build net fusion energy devices, enabling new players and new approaches to fusion energy at university and private company scale.</p>
                        <p>The way these high–field magnets slash the size of plants needed to achieve a given level of power has repercussions that reverberate through every aspect of the design. Components that would otherwise be so large that they would have to be manufactured on–site could instead be factory–built and trucked in; ancillary systems for cooling and other functions would all be scaled back proportionately; and the total cost and time for design and construction would be drastically reduced.</p>
                        <p>Hartwig states that “What you’re looking for is power production technologies that are going to play nicely within the mix that’s going to be integrated on the grid in 10 to 20 years." The grid right now is moving away from these two– or three–gigawatt monolithic coal or fission power plants. The range of a large fraction of power production facilities in the U.S. is now is in the 100 to 500 megawatt range. The technology has to be amenable with what sells to compete robustly in a brutal marketplace</p>
                        <p>Because the magnets are the key technology for the new fusion reactor, and because their development carries the greatest uncertainties, Whyte explains, work on the magnets will be the initial three–year phase of the project — building upon the strong foundation of federally–funded research conducted at MIT and elsewhere. Once the magnet technology is proven, the next step of designing the SPARC tokamak is based on a relatively straightforward evolution from existing tokamak experiments, he says.</p>
                        <p>The SPARC research project aims to leverage the scientific knowledge and expertise built up over decades of government–funded research — including MIT’s work, from 1971 to 2016, with its Alcator C–Mod experiment, as well as its predecessors — in combination with the intensity of a well–funded startup company. Whyte, Greenwald, and Hartwig say that this new approach could greatly shorten the time to bring fusion technology to the marketplace — while there’s still time for fusion to make a real difference in climate change.</p>
                    <h4>MITEI participation</h4>
                        <p>Commonwealth Fusion Systems is a private company and will join the MIT Energy Initiative (MITEI) as part of a new university–industry partnership built to carry out this plan. The collaboration between MITEI and CFS is expected to bolster MIT research and teaching on the science of fusion, while at the same time building a strong industrial partner that ultimately could be positioned to bring fusion power to real–world use.</p>
                        <p>Director Robert Armstrong of MITEI has created a new membership specifically for energy startups, and CFS is the first company to become a member through this new program at MIT. In addition to providing access to the significant resources and capabilities of the Institute, the membership is designed to expose startups to incumbent energy companies and their vast knowledge of the energy system. It was through their engagement with MITEI that ENI, one of MITEI’s founding members, became aware of SPARC’s potential for revolutionizing the energy system.</p>
                        <p>Energy startups often require significant research funding to further their technology to the point where new clean energy solutions can be brought to market. Traditional forms of early–stage funding are often incompatible with the long lead times and capital intensity that are well–known to energy investors.</p>
                        <p>Dr. Greenwald states that the magnets can be successfully developed to meet the needs of the task. Others have built magnets using this material, for other purposes, which had twice the magnetic field strength that will be required for this reactor. Though these high–field magnets were small, they do validate the basic feasibility of the SPARC concept.</p>
                        <p>SPARC has an agreement with MITEI to fund fusion research projects run out of PSFC’s Laboratory for Innovation in Fusion Technologies. The expected investment in these research projects amounts to about $2 million in the coming years.</p>
                        <p>SPARC is an evolution of a tokamak design that has been studied and refined for decades. This included work at MIT that began in the 1970s, led by professors Bruno Coppi and Ron Parker, who developed the kind of high–magnetic–field fusion experiments that have been operated at MIT ever since, setting numerous fusion records.</p>
                        <p>The strategy is to use conservative physics, based on decades of work at MIT and elsewhere, Greenwald states that “If SPARC does achieve its expected performance, my sense is that’s sort of a Kitty Hawk moment for fusion, by robustly demonstrating net power, in a device that scales to a real power plant."</p>
                <h2>Quantitative Comparisons of Electron–Scale Turbulence Measurements in NSTX via Synthetic Diagnostics for High–<span className="math inline"><em>k</em></span> Scattering</h2>
                    <p>Two synthetic diagnostics are implemented for the high–<span className="math inline"><em>k</em></span> scattering system in National Spherical Torus Experiment (NSTX) [<em>Smith, et al.</em> (2008)] allowing direct comparisons between synthetic and experimentally detected frequency and wavenumber spectra of electron–scale turbulence fluctuations. Synthetic diagnostics are formulated in real space and in wavenumber space, and deployed to realistic electron–scale simulations carried out with the GYRO code [<em>Candy and Waltz</em> (2003). A highly unstable ETG regime (electron temperature gradient mode) in a modest–<span className="math inline"><em>β</em></span> NSTX NBI–heated H–mode discharge is chosen for the analysis. Mapping the measured wavenumbers to field–aligned coordinates shows that the high–<span className="math inline"><em>k</em></span> system is sensitive to fluctuations that are closer to the spectral peak in the density fluctuation wavenumber spectrum (streamers) than originally predicted. Analysis of synthetic spectra show that the frequency response of the detected fluctuations is dominated by Doppler shift and insensitive to the turbulence drive. The shape of the high–<span className="math inline"><em>k</em></span> density fluctuation wavenumber spectrum is sensitive to the ETG turbulence drive conditions, and can be reproduced in a sensitivity scan of the most pertinent turbulent drive terms in the simulation.</p>
                    <p>Plasma turbulence gives rise to anomalous transport of particles and heat in magnetic confinement fusion devices [<em>Horton</em> (1999)], resulting detrimental to confinement. The complex, kinetic nature of the turbulence has led to the development of sophisticated gyrokinetic models implemented in state–of–the–art numerical simulation [<em>Garbet, et al.</em> (2010)] (nonlinear gyrokinetic simulation) to study the turbulence and consequent turbulence–driven transport. The gyrokinetic model requires extensive validation in today’s fusion experiments before achieving a predictive capability for future fusion devices such as ITER [<em>Doyle, et al.</em> (2007)], FNSF [<em>Menard, et al.</em> (2011)] and beyond. Confidence in the predictions from gyrokinetic simulation can be gained via a thorough validation process, which should include detailed comparisons of turbulence characteristics in addition to the traditional comparisons of turbulent fluxes [<em>Terry, et al.</em> (2008), <em>Greenwald</em> (2010)]. In this section we make direct comparisons of density fluctuation spectra between experimental turbulence measurements by high–<span className="math inline"><em>k</em></span> scattering and nonlinear gyrokinetic simulations, which are part of an extensive validation study of electron thermal transport in NSTX [<em>Ruiz-Ruiz, et al.</em> (2019)]</p>
                    <p><span>175</span></p>
                    
                <p>Candy, J. and Waltz, R. E. (2003). An Eulerian gyrokinetic–Maxwell solver, <em>J. Comput. Phys.</em> <strong>186</strong>, p. 545, <a href="https://doi.org/10.1016/S0021-9991(03)00079-2">https://doi.org/10.1016/S0021-9991(03)00079-2</a>.</p>
                <p>Doyle, E. J., Houlberg, W. A., Kamada, Y., Mukhovatov, V., Osborne, T. H., Polevoi, A., Bateman, G., Connor, J. W., Cordey, J. G., Fujita, T., Garbet, X., Hahm, T. S., Horton, L. D., Hubbard, A. E., Imbeaux, F., Jenko, F., Kinsey, J. E., Kishimoto, Y., Li, J., Luce, T. C., Martin, Y., Ossipenko, M., Parail, V., Peeters, A., Rhodes, T. L., Rice, J. E., Roach, C. M., Rozhansky, V., Ryter, F., Saibene, G., Sartori, R., Sips, A. C. C., Snipes, J. A., Sugihara, M., Synakowski, E. J., Takenaga, H., Takimuka, T., Thomsen, K., Wade, M. R., Wilson, H. R., ITPA Transport Physics Topical Group, ITPA Confinement Database and Modeling Topical Group and ITPA Pedestal and Edge Topical Group, Chapter 2: Plasma confinement and transport, <em>Nucl. Fusion</em> <strong>47</strong>, pp. S18–S127, <a href="https://doi.org/10.1088/0029-5515/47/6/S02">https://doi.org/10.1088/0029-5515/47/6/S02</a>.</p>
                <p>Garbet, X., Idomura, Y., Villard, L. and Watanabe, T. H. (2010). Gyrokinetic simulations of turbulent transport, <em>Nucl. Fusion</em> <strong>50</strong>, p. 043002, <a href="https://doi.org/10.1088/0029-5515/50/4/043002">https://doi.org/10.1088/0029-5515/50/4/043002</a>.</p>
                <p>Horton, W. (1999). Drift waves and transport, <em>Rev. Mod. Phys.</em> <strong>71</strong>, p. 735, <a href="http://dx.doi.org/10.1103/RevModPhys.71.735">http://dx.doi.org/10.1103/RevModPhys.71.735</a>.</p>
                <p>Houshmandyar, S., Yang, Z. J., Phillips, P. E., Rowan, W., Hubbard, A. E., Rice, J. E., Hughes, J. W. and Wolfe, S. M. (2016). Temperature gradient scale length measurement: A high accuracy application of electron cyclotron emission without calibration, <span><em>Rev. Sci. Instrum.</em></span> <strong>87</strong>, p. 11E101, <a href="https://doi. org/10.1063/1. 4955297">https://doi. org/10.1063/1. 4955297</a>.</p>
                <p>Houshmandyar, S., Yang, Z. J., Liao, K. T., Zhao, B., Phillips, P. E., Rowan, W. L., Cao, N., Ernst, D. R. and Rice, J. E. (2017). Electron profile stiffness and critical gradient length studies in the Alcator C–Mod Tokamak, <span><em>Division of Plasma Physics Meeting</em></span> JP11.00092, <a href="http://meetings.aps.org/link/BAPS.2017.DPP.JP11.92">http://meetings.aps.org/link/BAPS.2017.DPP.JP11.92</a>.</p>
                <p>Ruiz Ruiz, J., Ren, Y., Guttenfelder, W., White, A. E., Kaye, S. M., Leblanc, B. P., Mazzucato, E., Lee, K. C., Domier, C. W., Smith, D. R. and Yuh, H. (2015). Stabilization of electron–scale turbulence by electron density gradient in national spherical torus experiment, <em>Phys. Plasmas</em> <strong>22</strong>, p. 122501, <a href="https://doi.org/10.1063/1.4936110">https://doi.org/10.1063/1.4936110</a>.</p>
                <p>Smith, D. R., Mazzucato, E., Lee, W., Park, H. K., Domier, C. W. and Luhmann, Jr., N. C. (2008). A collective scattering system for measuring electron gyroscale fluctuations on the National Spherical Torus Experiment, <em>Rev. Sci. Instrum.</em> <strong>79</strong>, p. 123501, <a href="https://doi.org/10.1063/1.3039415">https://doi.org/10.1063/1.3039415</a>.</p>
                <p>Terry, P. W., Greenwald, M., Leboeuf, J.–N., McKee, G. R., Mikkelsen, D. R., Nevins, W. M., Newman, D. E., Stotler, D. P., Task Group on Verification and Validation, U. S. Burning Plasma Organization, and U. S. Transport Task Force, <em>Phys. Plasmas</em> <strong>15</strong>, p. 062503, <a href=""></a>.</p>

            </div>
            
        )
    }
}
